/*
* Ce fichier associe chaque clé de ressource (nettoyée : sans espaces, sans caractères spéciaux)
* à son URL de fichier PDF externe correspondante.
* Les liens sont basés sur le fichier HTML que vous avez fourni.
* Si le lien n'est pas disponible (class="no-link" dans votre source), la valeur est null.
* NOTE : Les clés sont générées en remplaçant /, :, ' , ? , ( et ) par des underscores.
*/
const pdfLinks = {
    // ==================================================================================================================================================================================================================================================================================
    // BLOC 1
    // ==================================================================================================================================================================================================================================================================================
    'B1_M01_S000-Comment_et_pourquoi_se_former_à_la_conception_et_spécification_d_une_solution_digitale': null,
    'B1_M01_S001-La_veille_et_l_innovation': 'https://drive.google.com/file/d/1Ay_HMjmLBJYKwwzeyJIeFnHhyLvG1X-b/view?usp=drivesdk',
    'B1_M01_S002-Les_modes_d_innovation': 'https://drive.google.com/file/d/1pG-rNTO9zMhuJMjPvPE0_5of04lnrFtK/view?usp=drivesdk',
    'B1_M01_S003-Les_entreprises_et_l_innovation': 'https://drive.google.com/file/d/1vSo-pRzbNThNhAyrddn6CWptn4impdKD/view?usp=drivesdk',
    'B1_M01_S004-La_créativité_moteur_de_l_innovation': 'https://drive.google.com/file/d/1tODRjTqppJUo0zrtick37bVkRg7TvW2f/view?usp=drivesdk',
    'B1_M01_S005-Panorama_des_techniques_de_créativité': 'https://drive.google.com/file/d/1i5alCymO1ww1Fr-WhP5dMetpuhgSiDQ0/view?usp=drivesdk',
    'B1_M01_S006-L_écosystème_d_un_projet_digital': 'https://drive.google.com/file/d/1-IV5ce2tUFueTUhyGGbUKnzZsIL8tgWr/view?usp=drivesdk',
    'B1_M01_S007-Étude_comparative,_le_benchmark_des_solutions_existantes': 'https://drive.google.com/file/d/1EI6qDWEjGgCOLpUZEv0iasOw5ykxV61g/view?usp=drivesdk',
    'B1_M01_S008-Définir_la_cible_de_la_solution_digitale': 'https://drive.google.com/file/d/1WTBQFPd32eCxF_N_kYY14-YUSNx5WluL/view?usp=drivesdk',
    'B1_M01_S009-Les_principaux_acteurs_d_un_projet_digital_-_la_maîtrise_d_oeuvre': null,
    'B1_M01_S010-Les_principaux_acteurs_d_un_projet_digital_-_la_maîtrise_d_ouvrage': 'https://drive.google.com/file/d/1zt3sVe_5-QUDfK-1QDyVp68euC02jQND/view?usp=drivesdk',
    'B1_M01_S011-Identifier_les_parties_prenantes': 'https://drive.google.com/file/d/1GcN8x_1WKz_KifwL-0a-Xk9XbCDIy5vz/view?usp=drivesdk',
    'B1_M01_S012-Etablir_la_gouvernance_du_projet,_définir_les_rôles_et_les_responsabilités': 'https://drive.google.com/file/d/1m3zewoW_38SkDehJekQjvqKvYQwEqK2L/view?usp=drivesdk',
    'B1_M01_S013-Comprendre_les_enjeux_et_les_retombées_d_un_projet': 'https://drive.google.com/file/d/1HEewL7lvn4JWQa_-GjgBzZUyFwOtmfxW/view?usp=drivesdk',
    'B1_M01_S014-Le_cahier_des_charges_-_l_expression_du_besoin': 'https://drive.google.com/file/d/1oWx5iG5I7QL-dK40Y_fk2UTffIP1FTKe/view?usp=drivesdk',

    'B1_M02_S001-Les_spécificités_du_projet_digital': 'https://drive.google.com/file/d/1F-lZllIrOoKyIcs2K2H7NuQQ0kZ4X2-t/view?usp=drivesdk',
    'B1_M02_S002-Le_recueil_de_l_analyse_des_besoins': null,
    'B1_M02_S003-Définir_la_solution_et_le_projet_cibles': 'https://drive.google.com/file/d/1XsyFSg0NfRwS3QxDlT7FDiTbWhwY2yyS/view?usp=drivesdk',
    'B1_M02_S004-Définir_les_objectifs_et_faire_valider_l_opportunité_du_projet': 'https://drive.google.com/file/d/1ok0sXXdsa8eQ4lOkuM3nqNGaTcaFapnq/view?usp=drivesdk',
    'B1_M02_S005-Le_choix_technologique_de_la_solution': 'https://drive.google.com/file/d/1CSzqwGkNzPgXs61Wm2rhun4lCyN1XNIv/view?usp=drivesdk',
    'B1_M02_S006-Le_cahier_des_charges_technique_détailler_la_mise_en_oeuvre': 'https://drive.google.com/file/d/11ptBQ0Z5PSdpUWWKjqHPZ7uBmtvmudHO/view?usp=drivesdk',
    'B1_M02_S007-Le_cahier_des_charges_technique_du_besoin_à_la_solution_technique': 'https://drive.google.com/file/d/1c5V0YK-SLFs7TAyxw-vyxiYUyNgEG_w9/view?usp=drivesdk',
    'B1_M02_S008-Le_cahier_des_charges_technique_description_fonctionnelle_et_technique': 'https://drive.google.com/file/d/1JvrSP_Gyh3QRDgIy40hMj5FKNc1JJ7fM/view?usp=drivesdk',
    'B1_M02_S009-La_présentation_et_la_validation_de_sa_solution': 'https://drive.google.com/file/d/1tNXPDgwLFiYxwUr0lJ1CWLgnsX7i1_Ht/view?usp=drivesdk',
    'B1_M02_S010-L_utilisation_en_interne_du_CDC': 'https://drive.google.com/file/d/1IoCa64CVosxeMcLiyEVIPf2UIuKY48XR/view?usp=drivesdk',

    'B1_M03_S001-Présentation_générale': null,
    'B1_M03_S002-Gestion_des_documents': null,
    'B1_M03_S003-Les_outils_de_dessin_vectoriel': null,
    'B1_M03_S004-Les_textes': 'https://drive.google.com/file/d/1Jx3Qv6tQJNCuc_Xs_9vl9cyln1_CLkuJ/view?usp=drivesdk',
    'B1_M03_S005-Importation_de_fichiers_et_d_images': null,
    'B1_M03_S006-Les_différents_effets_graphiques': null,
    'B1_M03_S007-Création_d_éléments_répétés': null,
    'B1_M03_S008-Redimensionnement_réactif': null,
    'B1_M03_S009-Utilisation_des_composants': null,
    'B1_M03_S010-Utilisation_et_gestion_des_Actifs': null,
    'B1_M03_S011-Le_mode_Prototype': null,
    'B1_M03_S012-Plug-ins': null,
    'B1_M03_S013-Partage_de_designs_et_de_prototypes': null,
    'B1_M03_S014-Les_différents_types_d_export': null,

    'B1_M04_S001-Présentation_de_l_application': 'https://drive.google.com/file/d/1IlDOlKPyR8q8p_0mbLyIWfiKqkBjZj6U/view?usp=drivesdk',
    'B1_M04_S002-L_application_Figma': 'https://drive.google.com/file/d/1S2QZ3u0j1f4ebqMkPdoXKzSbt5lRVQC2/view?usp=drivesdk',
    'B1_M04_S003-Importation_et_exportation_de_fichiers,_utilisation_de_modèles': 'https://drive.google.com/file/d/1GmRxtyz4hoZj5KD_tKTMpkLWe-TDbBQh/view?usp=drivesdk',
    'B1_M04_S004-Conception_avancée_menu_déroulant,_incrustation_d_écran,_personnaliser_le_design': 'https://drive.google.com/file/d/1-ToRK3cDGU6l9ZLE1DemTnP7itbeaGfj/view?usp=drivesdk',
    'B1_M04_S005-Créer_un_prototype,_partager_et_exporter': 'https://drive.google.com/file/d/1yZGlMN8E0jWqgndQqWCfxgQRc18NcHZx/view?usp=drivesdk',

    'B1_M05_S001-Introduction_à_l_organisation_d_un_projet_digital': 'https://drive.google.com/file/d/1xdKS2lJ-otA35gZna4dBRt9kECNJkBym/view?usp=drivesdk',
    'B1_M05_S002-Méthodologie_pour_piloter_un_projet_digital_une_démarche_itérative': 'https://drive.google.com/file/d/1uFGwTCh8JTkPEhBIIdA5jPfokSoS-xYy/view?usp=drivesdk',
    'B1_M05_S003-Le_rôle_du_chef_de_projet_digital': 'https://drive.google.com/file/d/167Ko4lFnKaEDNotc5xrcCDIGmHn5Y6On/view?usp=drivesdk',
    'B1_M05_S004-Les_modes_de_gestion_de_projet_dits_"classiques"': null,
    'B1_M05_S005-Les_méthodologies_agiles': null,
    'B1_M05_S006-Les_processus_et_les_disciplines_de_la_gestion_de_projet_selon_le_PMBOK': 'https://drive.google.com/file/d/1jYCLWmoRWzIeXMWVH1NsMQJaDZlG7Svw/view?usp=drivesdk',
    'B1_M05_S007-Les_acteurs_et_les_ressources_du_projet': 'https://drive.google.com/file/d/1WMAMrO1f-szMX4KfBuG2AP8mQDqO9eMo/view?usp=drivesdk',
    'B1_M05_S008-La_première_découpe_du_projet': 'https://drive.google.com/file/d/1O4dVFa--lhtpGn47CPtBKPjbyvyUlRBz/view?usp=drivesdk',
    'B1_M05_S009-La_construction_du_planning': 'https://drive.google.com/file/d/1fQH5RenmYofo-JQ0G-r37goUo_Ibe0Mo/view?usp=drivesdk',
    'B1_M05_S010-La_gestion_du_budget_du_projet': 'https://drive.google.com/file/d/1pz8xJtUOPmwHESBNX8Vlj7YEkR_fV-nP/view?usp=drivesdk',
    'B1_M05_S011-La_gestion_des_risques': 'https://drive.google.com/file/d/1saQIqcGH9NMx5vokt40wcGODrY7bHSAs/view?usp=drivesdk',
    'B1_M05_S012-La_communication_autour_du_projet': 'https://drive.google.com/file/d/1LLF3XNT8qDKH2W3707wENwDvgawZBA_6/view?usp=drivesdk',

    'B1_M06_S001-La_réalisation_d_une_étude_d_opportunité': 'https://drive.google.com/file/d/1JEyvdC9BE8g7GhUOgX8p1BYpNSOSusFG/view?usp=drivesdk',
    'B1_M06_S002-Le_rôle_de_la_note_de_cadrage': 'https://drive.google.com/file/d/1Gp_24KtEbAFdB1VdvslmAZyUZDHMsXWq/view?usp=drivesdk',
    'B1_M06_S003-L_étude_de_faisabilité': 'https://drive.google.com/file/d/1W-vhrBGXNdNv9gapUe5tfFbY9fGZWyD1/view?usp=drivesdk',
    'B1_M06_S004-L_analyse_des_risques': 'https://drive.google.com/file/d/1YEV1QXDqhrFYSX3I6kY3l9nS2JxyVBqX/view?usp=drivesdk',
    'B1_M06_S005-L_analyse_fonctionnelle': 'https://drive.google.com/file/d/17E2M3vCNhcV_aj5-5FuUDc1mVlV5JAwU/view?usp=drivesdk',
    'B1_M06_S006-Proposer_une_solution_optimale_en_termes_de_coût': 'https://drive.google.com/file/d/1awcBbAXh0GTPiJr0qKsIfQOndM4MQ9oz/view?usp=drivesdk',
    'B1_M06_S007-Proposer_une_solution_optimale_en_termes_de_délais_de_production': null,
    'B1_M06_S008-Proposer_une_solution_optimale_en_termes_de_performance_attendue': 'https://drive.google.com/file/d/1JV8Wu36iiA9gb421ULLgBtoPv0iK5wic/view?usp=drivesdk',
    'B1_M06_S009-Proposer_une_solution_optimale_en_termes_de_pérennité': 'https://drive.google.com/file/d/1PvET66NMBEHKvMONRT6B47pMKAh9duvo/view?usp=drivesdk',
    'B1_M06_S010-L_utilité_du_suivi_de_la_performance': 'https://drive.google.com/file/d/1XCq6708hXvrFZfjlSXNSu2C9Za5qPnCv/view?usp=drivesdk',
    'B1_M06_S011-Les_indicateurs_de_suivi_selon_les_objectifs': 'https://drive.google.com/file/d/1m5wQvrFV1XizHg6n5E7CDXcbKXJEMHgH/view?usp=drivesdk',
    'B1_M06_S012-La_construction_d_un_tableau_de_bord_opérationnel': 'https://drive.google.com/file/d/1nX21eHp78JiXhnFtk5Nq7r1xbCjL-WQB/view?usp=drivesdk',

    'B1_M07_S001-Les_méthodologies_agiles': 'https://drive.google.com/file/d/18KcvswvC6B8jdEI06oBpYrCpp55SPg9P/view?usp=drivesdk',
    'B1_M07_S002-Introduction_à_la_méthode_Scrum': 'https://drive.google.com/file/d/1lyxqaWfljGOVrvIp_obsKJs-FQDWFTpr/view?usp=drivesdk',
    'B1_M07_S003-Comprendre_Kanban': 'https://drive.google.com/file/d/1Hi8B-FOW7kvD2MRMuiw1I03vrQVnrrkM/view?usp=drivesdk',
    'B1_M07_S004-Présentation_du_diagramme_de_Gantt': 'https://drive.google.com/file/d/1Lbm8o7fYdMrlitf1Rui9ZWuKB6MZlxOk/view?usp=drivesdk',

    'B1_M08_S001-L_architecture_en_appels_et_retours': 'https://drive.google.com/file/d/1xavRPD901FvTPISiv3CxT7-PC1UCivFg/view?usp=drivesdk',
    'B1_M08_S002-L_architecture_en_couches': 'https://drive.google.com/file/d/18ylydO1F_3V_lnTcWH927RVBPo8Vck9A/view?usp=drivesdk',
    'B1_M08_S003-L_architecture_centrée_sur_les_données': 'https://drive.google.com/file/d/1rZU2zRy7NwRz5-eaus_tovHG1P6P7RWs/view?usp=drivesdk',
    'B1_M08_S004-L_architecture_en_flot_de_données': 'https://drive.google.com/file/d/1dTyr079mFxQhnrPwI6mAurNsQuNoldj0/view?usp=drivesdk',
    'B1_M08_S005-L_architecture_orientée_objets': 'https://drive.google.com/file/d/1w6Q7g-z9KRb01w9kfsjqZN4th5WUh-ka/view?usp=drivesdk',
    'B1_M08_S006-L_architecture_orientée_agents': 'https://drive.google.com/file/d/15rJYu_dvH5UwrjrsmpMPVgfb5oaJJ_p5/view?usp=drivesdk',

    'B1_M09_S001-Comprendre_les_objectifs_de_la_spécification_fonctionnelle': 'https://drive.google.com/file/d/1lK6coiqM73i7Sc7PhY5TNfa2hbojNnuo/view?usp=drivesdk',
    'B1_M09_S002-Comment_rédiger_une_spécification_fonctionnelle': 'https://drive.google.com/file/d/1WpbEMoowtwhYZ8RXMVTRnui_Jrnva-vz/view?usp=drivesdk',

    'B1_M10_S001-Le_cahier_des_charges_fonctionnel_le_contexte_du_projet_et_ses_enjeux': 'https://drive.google.com/file/d/19e1TX5o_B6-RFaJZWEs-qNhuixpAgHZN/view?usp=drivesdk',
    'B1_M10_S002-Le_cahier_des_charges_fonctionnel_la_portée_de_la_solution': 'https://drive.google.com/file/d/1bCWzQH0m1DY9Eby9YSb9PXZmJ5l17QGF/view?usp=drivesdk',
    'B1_M10_S003-Le_cahier_des_charges_fonctionnel_les_contraintes': 'https://drive.google.com/file/d/1ZU_2jSIO9RhqbxdCVni1HnwwWNIytTC6/view?usp=drivesdk',
    'B1_M10_S004-Le_cahier_des_charges_fonctionnel_les_parcours_utilisateurs': 'https://drive.google.com/file/d/1j1nB3W60UsD_-8rcUhViBRhP0AL_r-UY/view?usp=drivesdk',
    'B1_M10_S005-Le_cahier_des_charges_fonctionnel_les_fonctionnalités_clés_et_les_spécifications': 'https://drive.google.com/file/d/14DPSHcW41pMKjX9Dmf0HU8YYtSVtAInv/view?usp=drivesdk',
    'B1_M10_S006-Le_cahier_des_charges_fonctionnel_l_approche_créative': 'https://drive.google.com/file/d/1Nk5KkhYn4JUzPUdrFfB4gd2IbMvQsIJ8/view?usp=drivesdk',
    'B1_M10_S007-Le_cahier_des_charges_fonctionnel_l_organisation_du_projet': 'https://drive.google.com/file/d/1D9SbaiYdiG0TQQ2VHs27kXj_Ojp0-g4d/view?usp=drivesdk',

    'B1_M11_S001-Le_recueil_et_l_analyse_des_besoins': 'https://drive.google.com/file/d/1xcR6wAl_AOV0HR9WV4F1kY6pNfUjp3Ao/view?usp=drivesdk',
    'B1_M11_S002-La_validation_de_la_solution': 'https://drive.google.com/file/d/1ewnX2Enrz0nnDcCNYGG4FO5yhn63v4vo/view?usp=drivesdk',
    'B1_M11_S003-Le_droit_du_web': 'https://drive.google.com/file/d/1GAQd9y3qFr3dB_GEj5IPSY_d0dXqdPNz/view?usp=drivesdk',
    'B1_M11_S004-Définition_du_droit_numérique': 'https://drive.google.com/file/d/1VOb_q8aRp53lvbcAxeXYVuVFTSvthFMK/view?usp=drivesdk',
    'B1_M11_S005-Les_responsabilités_des_intervenants': 'https://drive.google.com/file/d/1vxa6mvk5WdBMfsp6WX-vmh-etA3Cdm0T/view?usp=drivesdk',
    'B1_M11_S006-Le_droit_pénal_de_l_informatique': 'https://drive.google.com/file/d/1L1kGLBlE-S-77sJ1A15MLTuxIX1CkyuB/view?usp=drivesdk',
    'B1_M11_S007-L_informatique_sur_le_lieu_de_travail': 'https://drive.google.com/file/d/1rVKOfUUfqlyk07W1pszNZ_40zZiHZL3A/view?usp=drivesdk',
    'B1_M11_S008-La_législation_comparée': 'https://drive.google.com/file/d/1nIj5ld0RyW6V-vxqviBAq-Wy8XqrxS5h/view?usp=drivesdk',
    'B1_M11_S009-L_informatique_et_droit_public': 'https://drive.google.com/file/d/1CIMqRy-Ofvj3f60BV_6YzMQDb6YfKSFn/view?usp=drivesdk',
    'B1_M11_S010-Le_cadre_juridique_du_e-commerce': 'https://drive.google.com/file/d/1kbfLmVzTYvet3O71EKXChufpzrkH4yy7/view?usp=drivesdk',
    'B1_M11_S011-Les_textes_de_référence': null,

    // ==================================================================================================================================================================================================================================================================================
    // BLOC 2
    // ==================================================================================================================================================================================================================================================================================
    'B2_M01_S001-L_application_Trello': null,
    'B2_M01_S002-Création_du_compte': null,
    'B2_M01_S003-Découverte_de_l_interface': null,
    'B2_M01_S004-Découvrir_le_contenu_d_un_projet': null,
    'B2_M01_S005-Le_travail_collaboratif_les_membres': null,
    'B2_M01_S006-Le_travail_collaboratif_les_équipes': null,
    'B2_M01_S007-Les_tableaux': 'https://drive.google.com/file/d/1PR90K2AYEt0cVqkURabsXJSjeg2PfXuJ/view?usp=drivesdk',
    'B2_M01_S008-Les_listes': null,
    'B2_M01_S009-Les_cartes': null,
    'B2_M01_S010-Les_checklists': null,
    'B2_M01_S011-Les_utilitaires': null,
    'B2_M01_S012-Les_Power-ups': null,

    'B2_M02_S001-Découvrir_JIRA': null,
    'B2_M02_S002-Apprendre_JIRA': null,
    'B2_M02_S003-Les_méthodologies_agiles_avec_JIRA': null,
    'B2_M02_S004-JIRA_pour_les_équipes': null,
    'B2_M02_S005-JIRA_pour_les_administrateurs': null,
    'B2_M02_S006-Utiliser_JIRA_avec_Gitlab': null,

    'B2_M03_S001-Apprendre_à_utiliser_Gantt_project': null,
    'B2_M03_S002-Cadrer_le_projet': null,
    'B2_M03_S003-Construire_le_plan_de_projet': null,
    'B2_M03_S004-Création_des_dépendances': null,
    'B2_M03_S005-Gérer_les_affichages': null,
    'B2_M03_S006-Le_réseau_du_projet': null,
    'B2_M03_S007-Gérer_les_ressources': null,
    'B2_M03_S008-Le_suivi_de_projet': null,
    'B2_M03_S009-Les_outils_d_impression_et_d_exportation': null,
    'B2_M03_S010-Application_-_Gestion_de_projet_-_GanttProject': null,

    'B2_M04_S001-Introduction_à_la_modélisation_conceptuelle_de_données_avec_UML': 'https://drive.google.com/file/d/1U4iVgZD09HSMBsitLp47LDPMcxoRRkui/view?usp=drivesdk',
    'B2_M04_S002-Les_diagrammes_de_classes': null,
    'B2_M04_S003-Les_diagrammes_d_objets': 'https://drive.google.com/file/d/1D65pF0qlBCMGXWozUAnYyzx32OcXJYKv/view?usp=drivesdk',
    'B2_M04_S004-Les_diagrammes_de_composants': 'https://drive.google.com/file/d/1VZ_OiK1A7QZ6nBWJWZ2xnyzpYb1G7G7L/view?usp=drivesdk',
    'B2_M04_S005-Les_diagrammes_de_déploiement': 'https://drive.google.com/file/d/1FnaT9wgMJFH9Vor6wzI7iPtTGqyIyEzC/view?usp=drivesdk',
    'B2_M04_S006-Les_diagrammes_des_paquets': 'https://drive.google.com/file/d/1Vqzajd8bDkHMWgo69t2xBcuWkRervwOH/view?usp=drivesdk',
    'B2_M04_S007-Les_diagrammes_de_structure_composite': 'https://drive.google.com/file/d/13WGvoMPNDVObrcvj8NfcJ67RGdCsSGGH/view?usp=drivesdk',
    'B2_M04_S008-Les_diagrammes_de_profils': 'https://drive.google.com/file/d/1Q38M9lDgW0ROvEnM0Hru-lYC0L4hAj21/view?usp=drivesdk',
    'B2_M04_S009-Diagrammes_de_cas_d_utilisation_UML_(UML_use_case_diagram)': 'https://drive.google.com/file/d/16zm-wu5UizF516WXJEKb88VWc-fDW9lB/view?usp=drivesdk',
    'B2_M04_S010-Les_diagrammes_états-transitions': 'https://drive.google.com/file/d/1Zebxm4dLr-G3Kkw-CmpUuLh5lVdz-8VC/view?usp=drivesdk',
    'B2_M04_S011-Les_diagrammes_d_activité': 'https://drive.google.com/file/d/1gVYYzprOUjGWd_PKGf-NZiWr-3TPboQY/view?usp=drivesdk',
    'B2_M04_S012-Les_diagrammes_de_séquence': 'https://drive.google.com/file/d/1fiyz_YzR-c_0cweQUitEj-7W3jIuDJ1-/view?usp=drivesdk',
    'B2_M04_S013-Les_diagrammes_de_communication': 'https://drive.google.com/file/d/1Yk7BXJ9hKvTv1q9_cc7duZ9cOQyPx-sq/view?usp=drivesdk',
    'B2_M04_S014-Les_diagrammes_global_d_interaction': 'https://drive.google.com/file/d/1pVn1CNRUY9Ap8ShQ3jfPWl2wGm4kX87n/view?usp=drivesdk',
    'B2_M04_S015-Les_diagrammes_de_temps': 'https://drive.google.com/file/d/19ZM6I5TB_4JE9R-Rxg9hsqPytymL3BiY/view?usp=drivesdk',

    'B2_M05_S001-Comprendre_les_différents_cycles_de_vie_des_projets_en_méthode_Agile': null,
    'B2_M05_S002-Définir_le_cadre_de_la_solution_digitale': 'https://drive.google.com/file/d/1_Nuu75GCB82rhbGStEcZc0YjGGI0Vf8M/view?usp=drivesdk',
    'B2_M05_S003-La_préparation_du_backlog': 'https://drive.google.com/file/d/1pFePTrL2l6SU8c7yPG6av4NQutuZ4pbR/view?usp=drivesdk',
    'B2_M05_S004-La_notion_de_travail_en_sprint': 'https://drive.google.com/file/d/1kE3ZuyRZjvFyVXauhBuBu_D-E3twya23/view?usp=drivesdk',
    'B2_M05_S005-Les_retours_et_les_feedbacks': null,
    'B2_M05_S006-La_réitération_en_fonction_des_feedbacks': null,
    'B2_M05_S007-Le_rôle_du_Scrum_Master': null,
    'B2_M05_S008-Le_rôle_du_product_owner': null,

    'B2_M06_S001-L_application_Smartsheet': null,
    'B2_M06_S002-La_plateforme_Monday': null,

    'B2_M07_S001L_examen_des_exigences': null, // Correction de clé
    'B2_M07_S002-Les_tests_d’usabilité': null,
    'B2_M07_S003-Les_tests_unitaires': 'https://drive.google.com/file/d/1BSG1MkfTJnqsGWFtl1I3LPTlWpZr80PV/view?usp=drivesdk',
    'B2_M07_S004-Les_tests_d’intégration': 'https://drive.google.com/file/d/1mNHxJFD660xqK2vdWURpzmB88c4IGwJD/view?usp=drivesdk',
    'B2_M07_S005-Les_tests_des_composants': 'https://drive.google.com/file/d/1b-89Vjgtfmfw0JbK8P4bMyMrIN4doBdN/view?usp=drivesdk',
    'B2_M07_S006-Les_tests_de_bout_en_bout_End_to_End': null, // Correction de clé
    'B2_M07_S007-Les_tests_d’acceptation': null,
    'B2_M07_S008-Les_tests_de_régression': null,
    'B2_M07_S009-Intégration_continue': 'https://drive.google.com/file/d/1pvRzjiKNTyElBSW-Qa-Zy-kvBn3tVlfj/view?usp=drivesdk',
    'B2_M07_S010-Le_déploiement_continu_(CD)': 'https://drive.google.com/file/d/1Al4jib4VCM6TRlWBFFaeZe0tZc3lZse2/view?usp=drivesdk',

    'B2_M08_S001-Les_notions_de_test_unitaire_et_test_fonctionnel': null,
    'B2_M08_S002-Les_tests_unitaires_avec_PHPUnit': 'https://drive.google.com/file/d/1QyXdTqDPgrXvUzU1n4iwKZVAO83lClBD/view?usp=drivesdk',
    'B2_M08_S003-Les_tests_fonctionnels_avec_WebTestCase_et_Panther': 'https://drive.google.com/file/d/1TBWgkPdTTrFS_EuXh0Mapv4lpDIiQ6y5/view?usp=drivesdk',
    'B2_M08_S004-Les_tests_unitaires_avec_les_mocks': 'https://drive.google.com/file/d/1nbusq4CRrYsGHv8SXzOS8RX6wnBDVPDE/view?usp=drivesdk',
    'B2_M08_S005-Le_Test_Driven_Development': 'https://drive.google.com/file/d/1DYsW5Hb73nYXGAZUuShoTTTYS4NMLFHE/view?usp=drivesdk',
    'B2_M08_S006-Les_services': 'https://drive.google.com/file/d/1VAITr-KWRWdY7cslCZOBARl5zXn-xEPu/view?usp=drivesdk',
    'B2_M08_S007-L_Ajax_avec_Axios_et_Symfony': 'https://drive.google.com/file/d/1bXyS9gXF0bbsXCbcTKF4QFg6fUSYU3n1/view?usp=drivesdk',
    'B2_M08_S008-Tests_d_intégration_et_recette_fonctionnelle': 'https://drive.google.com/file/d/1GeL8YZxuZ2Tq0ud2Vav3ell775zuDfiz/view?usp=drivesdk',
    'B2_M08_S009-Mesurer_son_application': 'https://drive.google.com/file/d/14BrSpdLpdbPgXD_3drC4urqejGb7K8IL/view?usp=drivesdk',
    'B2_M08_S010-A/B_testing': null,

    'B2_M09_S001-La_résolution_d_une_situation_critique_pour_la_survie_du_projet': 'https://drive.google.com/file/d/1x0Vy-J34GiOM7DSRokQgLFp66NS-c370/view?usp=drivesdk',
    'B2_M09_S002-Le_suivi_des_indicateurs_qualité_et_amélioration_continue': 'https://drive.google.com/file/d/1I0uN70Q1u1gTVKWzCVwqKJUlriSoFUBO/view?usp=drivesdk',
    'B2_M09_S003-La_conception_de_la_solution_grâce_au_Design_Thinking': 'https://drive.google.com/file/d/1K1KCHq7N8nWYEZyaVN41l_EnwNPXCF7I/view?usp=drivesdk',
    'B2_M09_S004-Design_Thinking_La_phase_d_empathie,_la_compréhension_du_besoin': 'https://drive.google.com/file/d/1m5xTmUQcIN5ez6iuMFtqd_V2mc7wK5Th/view?usp=drivesdk',
    'B2_M09_S005-Design_Thinking_Définir_la_problématique': 'https://drive.google.com/file/d/1Asj422Y9t_HF78WmJwGVSZqT0FdZXSHZ/view?usp=drivesdk',
    'B2_M09_S006-Design_Thinking_La_phase_d_idéation': 'https://drive.google.com/file/d/1-MoayOYhf8KeTuLiJXf2GhNQ0WBpIhaq/view?usp=drivesdk',
    'B2_M09_S007-Design_Thinking_La_phase_de_prototypage_de_la_solution': 'https://drive.google.com/file/d/1nMiX9sb7Nspgrj2lgkdeGeyLbgHyLVAh/view?usp=drivesdk',
    'B2_M09_S008-Design_Thinking_La_phase_de_test_de_la_solution': 'https://drive.google.com/file/d/1QH1gTSB49JoDSg8B4300YoiXG4OsZfLL/view?usp=drivesdk',

    // ==================================================================================================================================================================================================================================================================================
    // BLOC 3
    // ==================================================================================================================================================================================================================================================================================
    'B3_M01_S001-Comment_et_pourquoi_se_former_à_la_production_de_contenus_digitaux': null,
    'B3_M01_S002-Introduction_à_la_production_de_contenus_digitaux': 'https://drive.google.com/file/d/1KwRbunnQHeeDNXjIxMdXusdVMXEL_Qfs/view?usp=drivesdk',
    'B3_M01_S003-La_création_de_contenu_digital_en_adéquation_avec_sa_cible': 'https://drive.google.com/file/d/1te0EocV7CFWzRhGUIgyi0-VnkkzMagrZ/view?usp=drivesdk',
    'B3_M01_S004-L_orientation_artistique_et_le_brief_créatif': 'https://drive.google.com/file/d/1e2tvg1rqoZQtcLP6U0_EZTCX4ntSfWYH/view?usp=drivesdk',
    'B3_M01_S005-La_gestion_de_la_production_de_contenus_digitaux': 'https://drive.google.com/file/d/1-5wDuUxx7Nf7kfrMJDJjsNR6ucf2h6xf/view?usp=drivesdk',
    'B3_M01_S006-La_mise_en_place_opérationnelle_de_sa_stratégie_de_production_de_contenus': 'https://drive.google.com/file/d/1t-oB6MwjKOGUNwZvauMLGM9B9UKh9E8z/view?usp=drivesdk',
    'B3_M01_S007-La_proposition_de_production_de_contenu': 'https://drive.google.com/file/d/14I94L3pquTnPOp822OjtPwxI66vSrpFZ/view?usp=drivesdk',
    'B3_M01_S008-Application_-_Piloter_la_production_de_contenus_digitaux': null,

    'B3_M02_S001-Introduction_HTML_et_CSS': 'https://drive.google.com/file/d/17ITRalaEUVR9ebKMVTSFoDKsx1pFZikd/view?usp=drivesdk',
    'B3_M02_S002-Syntaxe_générale_de_HTML': 'https://drive.google.com/file/d/19VUOxt6NIcAiEauggR8v-laLb6CCfF01/view?usp=drivesdk',
    'B3_M02_S003-L_organisation_du_texte': 'https://drive.google.com/file/d/1nKm48M73xGXpt41udjCj3eHcCdDflfNq/view?usp=drivesdk',
    'B3_M02_S004-Un_langage_hypertexte': 'https://drive.google.com/file/d/1rydaJsj_ZyL0hGj8cjrXrGispK1OQE9A/view?usp=drivesdk',
    'B3_M02_S005-Le_multimédia_en_HTML': 'https://drive.google.com/file/d/1hQiCx_-GZOl_OntdY2iSX6gBhuOQDAvn/view?usp=drivesdk',
    'B3_M02_S006-Introduction_au_CSS': null,
    'B3_M02_S007-CSS3_Le_stylage_du_texte': 'https://drive.google.com/file/d/1-ERh-E-7d20fdU1ga3wBt6BCs8UxpWKQ/view?usp=drivesdk',
    'B3_M02_S008-La_structuration_logique_en_HTML5_et_le_modèle_de_boîtes_en_CSS3': 'https://drive.google.com/file/d/1BJZyC286WN1vbjkF7fX3hnxHlbuQnaVI/view?usp=drivesdk',
    'B3_M02_S009-Les_sélecteurs_CSS': 'https://drive.google.com/file/d/1_-Y_MhMZTaB_XeVMeI8Ud-cD7e6espHC/view?usp=drivesdk',
    'B3_M02_S010-La_mise_en_page_avec_CSS': 'https://drive.google.com/file/d/1n-DplBT80AaPivWWabBGnHDawrNYC0mD/view?usp=drivesdk',
    'B3_M02_S011-La_création_de_tableaux': 'https://drive.google.com/file/d/1kkunDQOMN6knlTbUqUZKADyW8KpolZNE/view?usp=drivesdk',
    'B3_M02_S012-La_création_de_formulaires': 'https://drive.google.com/file/d/13hJ4JAs1Yoib-eGKV3MDfC-VOY2IchWR/view?usp=drivesdk',
    'B3_M02_S013-Layout_avec_CSS_Grid': 'https://drive.google.com/file/d/1ERoXaNgtariaL9fcw5wfzB98wqAqYowt/view?usp=drivesdk',
    'B3_M02_S014-Les_effets_avancés_de_CSS': 'https://drive.google.com/file/d/1aCfxiP13_fheYo5JP-nvHdijy_gTnufA/view?usp=drivesdk',
    'B3_M02_S015-Utiliser_des_documentations_CSS': 'https://drive.google.com/file/d/1zxlqDKFODOKtBM680cjOFQQV5ADl4zgP/view?usp=drivesdk',
    'B3_M02_S016-Le_responsive_design': 'https://drive.google.com/file/d/1tfbvlnR0WdJUmvTH_8BIdGDR09k_cSEZ/view?usp=drivesdk',
    'B3_M02_S017-Valider_la_qualité_de_son_site': 'https://drive.google.com/file/d/1rcVm9ABNSp0VKYqbL9wtluTGi-iTh6oi/view?usp=drivesdk',
    'B3_M02_S018-L_installation_et_la_prise_en_main_du_framework_Bootstrap_-_Hello_world': 'https://drive.google.com/file/d/1qb8SP_EN4eOdK9po2FFnPDPgil4IwtMb/view?usp=drivesdk',
    'B3_M02_S019-La_grille_bootstrap': 'https://drive.google.com/file/d/1wpzbi3vDXsYCQaTYfCeu3dkU1nRPanTn/view?usp=drivesdk',
    'B3_M02_S020-Les_éléments_bootstrap': 'https://drive.google.com/file/d/13AiERGctGVNXwj7Z-Y5HYu1UBvHVExoc/view?usp=drivesdk',
    'B3_M02_S021-Les_composants_bootstrap': 'https://drive.google.com/file/d/16z6MZPMlnKtBKtaQxZaO0Vbk0Rl4gzuh/view?usp=drivesdk',
    'B3_M02_S022-Ouverture_vers_d_autres_framework_CSS': 'https://drive.google.com/file/d/1wi8tcPE3tCFlIJd1_9uyjI3xKtR6c602/view?usp=drivesdk',
    'B3_M02_S023-SASS': 'https://drive.google.com/file/d/1n-6QybV51Qg60O7Hmn9ECw-thHds-SDD/view?usp=drivesdk',
    'B3_M02_S024-Le_référencement_des_sites_Web': 'https://drive.google.com/file/d/1sTJXn_YP5Nef0evuRhnlEplseYE1WKQe/view?usp=drivesdk',
    'B3_M02_S025-Déployer_son_site_sur_le_Web': 'https://drive.google.com/file/d/15fAWKj1c5k-ND9aEkFINI2FoH4IQqaQn/view?usp=drivesdk',

    'B3_M03_S001-La_programmation_événementielle_en_JavaScript': null,
    'B3_M03_S002-Le_formulaire_HTML_et_JavaScript': null,
    'B3_M03_S003-Initiation_aux_objets_et_aux_classes': null,
    'B3_M03_S004-L_API_DOM': null,
    'B3_M03_S005-Présentation_de_la_librairie_JQuery': null,
    'B3_M03_S006-Les_bases_de_JQuery': null,
    'B3_M03_S007-La_programmation_AJAX': null,
    'B3_M03_S008-Les_promesses_et_l_API_Fetch': null,
    'B3_M03_S009-L_utilisation_de_JSON': null,
    'B3_M03_S010-L_API_Canvas_en_JavaScript': null,

    'B3_M04_S001-PHP_et_HTML_sorties': 'https://drive.google.com/file/d/1j3lWs4-oT7PK-3SxJKc3t9ALRQszzXwC/view?usp=drivesdk', // Correction de clé
    'B3_M04_S002-Les_types_de_données_les_variables_et_les_constantes': 'https://drive.google.com/file/d/1A3eb5tABXkUkIe0dWKaZxzboOnUCuVG-/view?usp=drivesdk', // Correction de clé
    'B3_M04_S003-Les_opérateurs_de_comparaison_et_les_expressions_booléennes': 'https://drive.google.com/file/d/1Y5UzV9oljKEVVKveeA92S4edSXdrWcjs/view?usp=drivesdk',
    'B3_M04_S004-Les_fonctions': 'https://drive.google.com/file/d/1Dx9n0fEjhRsqOLFfI__UqScxrLXgtA-y/view?usp=drivesdk',
    'B3_M04_S005-Les_tableaux': null,
    'B3_M04_S006-Les_conditions': 'https://drive.google.com/file/d/1UwR5Xj4uvzJPCF1U1CniSJZIRqnjG4BY/view?usp=drivesdk',
    'B3_M04_S007-Les_boucles': 'https://drive.google.com/file/d/1A--l1TCKBycRdaw42G4brrkJzzJRffGR/view?usp=drivesdk',
    'B3_M04_S008-Créer_ses_propres_fonctions': 'https://drive.google.com/file/d/15sG6gpDCUjgGP_dR7cltiJ1ai7knB-Du/view?usp=drivesdk',
    'B3_M04_S009-L_organisation_des_fichiers_PHP': 'https://drive.google.com/file/d/1Y8OWqzvvH5XR_oUGtk8kid5Wk8nr0ZX6/view?usp=drivesdk',
    'B3_M04_S010-Les_superglobales_Get_Post_et_Files': 'https://drive.google.com/file/d/14JhcnRwAWG-L6b7yUnfZoVAPOewoXbEu/view?usp=drivesdk', // Correction de clé
    
    'B3_M04_S011-Les_superglobales_Server_Env_et_Session': null,
    'B3_M04_S012-La_sécurité': null,
    'B3_M04_S013-La_manipulation_des_dates': null,
    'B3_M04_S014-La_manipulation_des_fichiers_en_PHP': null,
    'B3_M04_S015-Les_expressions_régulières': null,
    'B3_M04_S016-Utiliser_la_documentation_PHP_et_Standard_de_codage_PHP': null,
    'B3_M04_S017-La_préparation_de_l_environnement_de_travail': null,
    'B3_M04_S018-La_programmation_Orientée_Objet_concepts_de_base': null,
    'B3_M04_S019-La_programmation_Orientée_Objet_concepts_avancés': null,
    'B3_M04_S020-La_gestion_des_erreurs': null,
    'B3_M04_S021-La_programmation_Orientée_Objet_Design_Patterns': null,
    'B3_M04_S022-La_programmation_Orientée_Objet_L_encapsulation_et_la_visibilité': null,
    'B3_M04_S023-Le_modèle_MVC': null,

    'B3_M05_S001-Introduction_générale_aux_bases_de_données_notion_de_SGBDR': null,
    'B3_M05_S002-Modèle_conceptuel_de_données_et_modèle_logique_de_données': null,
    'B3_M05_S003-Les_diagrammes_fonctionnels': null,
    'B3_M05_S004-Le_diagramme_de_classe': null,
    'B3_M05_S005-Introduction_au_passage_UML-_Relationnel': null,
    'B3_M05_S006-Création_et_alimentation_de_bases_de_données_SQL': null,
    'B3_M05_S007-L_interrogation_de_bases_de_données_SQL': null,
    'B3_M05_S008-Découvrir_un_autre_SGBDR_PostgreSQL': null,
    'B3_M05_S009-Connexion_à_la_base_de_données_en_PHP': null,
    'B3_M05_S010-PHP_PDO_accès_en_lecture_écriture': null,
    'B3_M05_S011-Les_requetes_SQL': null,
    'B3_M05_S012-Les_fonctions_SQL': null,
    'B3_M05_S013-Les_jointures_SQL': null,
    'B3_M05_S014-Gérer_les_accès_des_utilisateurs_au_niveau_PHP_et_BD': null,
    'B3_M05_S015-Découverte_d_un_ORM_PHP': null,
    'B3_M05_S016-Projet_Créer_et_administrer_une_base_de_données': null,
    'B3_M05_S017-Introduction_NOSQL': null,
    'B3_M05_S018-Introduction_à_MongoDB': null,

    'B3_M06_S001-Introduction_NOSQL': null,
    'B3_M06_S002-Introduction_à_MongoDB': null,

    'B3_M07_S001-L_interpréteur_de_commande_Python': null,
    'B3_M07_S002-Environnements_de_travail': null,
    'B3_M07_S003-Variables_et_types_de_données': null,
    'B3_M07_S004-Portée_des_variables_et_notion_de_référence': null,
    'B3_M07_S005-Conditions_en_Python': null,
    'B3_M07_S006-Boucles_en_Python': null,
    'B3_M07_S007-Les_structures_de_données_en_Python': null,
    'B3_M07_S008-Structure_d_un_programme_-_fonctions': null,
    'B3_M07_S009-Améliorer_la_qualité_du_code': null,
    'B3_M07_S010-Structure_d_un_programme_-_modules': null,
    'B3_M07_S011-Améliorer_la_qualité_du_code_-_les_tests_unitaires': null,
    'B3_M07_S012-Notions_théoriques_de_classe': null,
    'B3_M07_S013-Constructeur_et_mot-clé_self': null,
    'B3_M07_S014-Les_méthodes_spéciales': null,
    'B3_M07_S015-L_héritage': null,
    'B3_M07_S016-La_notion_de_décorateur_en_Python': null,
    'B3_M07_S017-Chaîne_de_caractères_en_Python': null,
    'B3_M07_S018-La_gestion_du_temps_en_Python': null,
    'B3_M07_S019-Mathématiques_en_Python': null,
    'B3_M07_S020-Plus_loin_en_mathématiques': null,
    'B3_M07_S021-Visualiser_des_données_sous_formes_de_graphiques': null,
    'B3_M07_S022-Gestion_des_fichiers_en_Python': null,
    'B3_M07_S023-Requêtes_HTTP': null,
    'B3_M07_S024-Les_bases_de_données_relationnelles_et_Python': null,
    'B3_M07_S025-Notion_d_ORM_object-relational_mapping': null,
    'B3_M07_S026-Cadre_théorique_de_Flask': null,
    'B3_M07_S027-Le_moteur_de_template_Jinja': null,
    'B3_M07_S028-Déploiement_en_ligne_du_site_Flask': null,
    'B3_M07_S029-Cadre_théorique_de_Django': null,
    'B3_M07_S030-Les_modèles_en_Django': null,
    'B3_M07_S031-Les_vues_en_Django': null,
    'B3_M07_S032-API_REST_en_Python': null,
    'B3_M07_S033-La_data_visualisation_avec_Python': null,
    'B3_M07_S034-La_présentation_des_données_et_des_librairies': null,
    'B3_M07_S035-La_librairie_numpy': null,
    'B3_M07_S036-La_librairie_pandas_première_approche': null,
    'B3_M07_S037-Aller_plus_loin_avec_la_librairie_pandas': null,
    'B3_M07_S038-La_librairie_matplotlib': null,
    'B3_M07_S039-La_librairie_Seaborn': null,
    'B3_M07_S040-La_librairie_Bokeh': null,
    'B3_M07_S041-La_data_visualisation_avancée_avec_Streamlit': null,
    'B3_M07_S042-Des_présentations_de_résultats_impactantes': null,

    'B3_M08_S001-Le_développement_Mobile': null,
    'B3_M08_S002-Introduction_à_React_Native_l_outil_Expo': null,
    'B3_M08_S003-Les_bases_de_React_Native': null,
    'B3_M08_S004-Les_composants_React_Native': null,
    'B3_M08_S005-Les_props_et_les_states': null,
    'B3_M08_S006-Style_et_mise_en_page_avec_Flexbox': null,
    'B3_M08_S007-Du_code_différent_en_fonction_de_la_plateforme': null,
    'B3_M08_S008-L_utilisation_de_Redux': null,
    'B3_M08_S009-Les_extensions_de_Redux': null,
    'B3_M08_S010-L_organisation_d_une_application_React_Native': null,
    'B3_M08_S011-La_navigation_avec_React_Native': null,
    'B3_M08_S012-Les_différents_types_de_navigators': null,
    'B3_M08_S013-L_animation_avec_React_Native': null,
    'B3_M08_S014-Installer_les_émulateurs': null,
    'B3_M08_S015-Utiliser_une_base_données_locale_SQLITE': null,
    'B3_M08_S016-Les_APIs_React_Native_et_modules_natifs': null,
    'B3_M08_S017-Le_debugging': null,
    'B3_M08_S018-Le_déploiement_d_une_application_sur_les_stores': null,
    'B3_M08_S019-Créer_une_application_React_Native_sans_Expo': null,
    'B3_M08_S020-Projet_-_développer_une_application_mobile_avec_React_Native': null,

    'B3_M09_S001-Présentation_des_API': null,
    'B3_M09_S002-Concevoir_une_API': null,
    'B3_M09_S003-Gérer_les_accès_à_une_API': null,

    'B3_M10_S001-Les_API_d_authentification__OAuth__': null,
    'B3_M10_S002-Les_API_Google___AWS': null,
    'B3_M10_S003-Les_API_de_paiement': null,

    'B3_M11_S001-Introduction_à_la_ligne_de_commande': null,
    'B3_M11_S002-Introduction_à_Git_et_Github': null,
    'B3_M11_S003-Les_bases': null,
    'B3_M11_S004-Les_interactions_avec_le_dépôt_distant': null,
    'B3_M11_S005-Naviguer_dans_l_historique': null,
    'B3_M11_S006-La_gestion_des_branches': null,
    'B3_M11_S007-Les_branches_avec_Git_-_Rebaser': null,
    'B3_M11_S008-Les_bonnes_pratiques': null,
    'B3_M11_S009-Projet_-_Utiliser_Git_et_Github_pour_gérer_son_code_source': null,
    'B3_M11_S010-Introduction_à_Gitlab': null,

    'B3_M12_S001-La_documentation_de_l_architecture_et_du_code': null,
    'B3_M12_S002-Améliorer_sa_solution': null,
    'B3_M12_S003-La_documentation_pour_l_utilisateur': null,
    'B3_M12_S004-Le_pentest': null,
    'B3_M12_S005-Gestion_de_la_dette_technique': null,
};